let themeToggle = document.querySelector(".dark_mode_toggle");
console.dir(themeToggle);
let body = document.querySelector("body");
let about_me = document.querySelector(".about_me");
let skills = document.querySelector(".skills");
let projects = document.querySelector(".projects");
let contact_me = document.querySelector(".contact_me");
let sidebar = document.querySelector(".sidebar");
let degree = document.querySelector(".degree");
let name = document.querySelector(".name");
let html_name = document.querySelector(".html_name");
let css_name = document.querySelector(".css_name");
let flutter_name = document.querySelector(".flutter_name");
let dart_name = document.querySelector(".dart_name");
let c_name = document.querySelector(".c_name");
let cpp_name = document.querySelector(".cpp_name");
let js_name = document.querySelector(".js_name");
let python_name = document.querySelector(".python_name");
let ae_name = document.querySelector(".ae_name");
let ps_name = document.querySelector(".ps_name");
let figma_name = document.querySelector(".pr_name");
let blender_name = document.querySelector(".blender_name");
let mobile_info = document.querySelector(".mobile_info_skills");
themeToggle.onclick = () => {
    console.log("button was clicked");
    body.style.backgroundColor = "#121212";
    body.style.color = "#E0E0E0";
    body.style.backgroundImage = "none";
    about_me.style.color = "#E0E0E0";
    skills.style.color = "#E0E0E0";
    projects.style.color = "#E0E0E0";
    contact_me.style.color = "#E0E0E0";
    sidebar.style.backgroundColor = "#2F2F2F";
    themeToggle.style.backgroundImage = "url('moon_darkmode.svg')";
    themeToggle.style.height = "1.75rem";
    themeToggle.style.width = "1.75rem";
    themeToggle.style.filter = "invert()" + "opacity(50%)";
    themeToggle.style.backgroundColor="none";
    degree.style.color = "rgb(156, 156, 156)";
    name.style.gap = "1.2vw";
    html_name.style.color = "rgb(234, 234, 234)";
    css_name.style.color = "rgb(234, 234, 234)";
    flutter_name.style.color = "rgb(234, 234, 234)";
    dart_name.style.color = "rgb(234, 234, 234)";
    c_name.style.color = "rgb(234, 234, 234)";
    cpp_name.style.color = "rgb(234, 234, 234)";
    js_name.style.color = "rgb(234, 234, 234)";
    python_name.style.color = "rgb(234, 234, 234)";
    ae_name.style.color = "rgb(234, 234, 234)";
    ps_name.style.color = "rgb(234, 234, 234)";
    figma_name.style.color = "rgb(234, 234, 234)";
    blender_name.style.color = "rgb(234, 234, 234)";
    mobile_info.style.color=" rgb(234,234,234)";

}